CREATE TABLE IF NOT EXISTS abc (
  id INTEGER NOT NULL,
  __special_id__ INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS __def__ (
  id INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ghi (
  id INTEGER NOT NULL,
  __a0__ INTEGER,
  PRIMARY KEY (id)
);